### ISSUE TITLE
As a rule author, I would like rule schema documentation

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/conformance-rules-editor#106]
Schema documentation should be generated from the schema file.
Two potential options are:
https://github.com/coveooss/json-schema-for-humans
https://github.com/atlassian-labs/json-schema-viewer

Due to shortcomings of both of these tools, it may be better to just implement our own documentation generator based on the work we did for rule template generation

**Comment by RamilCDISC** [comment]
The Validation process is over, The AC is successfully implemented and issue is ready to be closed. The schema documentation now comes from the engine directly.

**Comment by RamilCDISC** [comment]
### Validation Summary
### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:

Change Review:
The changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the changes were reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run (following the fixed practice of running after each Issue Validation) to validate that the changes did not affect any functionality of the overall system.

### Test Execution:

> The regression tests were executed using the following command:
> python -m pytest tests/QARegressionTests

### Results:
After successful running of regression tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Change Reviews:** The change reviews conducted by QA teams was completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.

**Comment by gerrycampion** [comment]
Merged
