### ISSUE TITLE
Add diff functionality to highlight changes against saved rule

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/conformance-rules-editor#127]
Currently, comparing previous versions is not in scope, but this should facilitate the ability to do this in the future

AC
There is an additional tab or toggle to display the diff editor
The diff editor should show the modified rule vs the last saved rule (readonly)
The component uses monaco's diff editor

**Comment by RamilCDISC** [comment]
The acceptance criteria is fulfilled for this issue. The diff tab in the rule editor works as intended. I have attached a screenshot showing the fulfillment of the AC
<img width="1434" alt="Confermance - 127" src="https://github.com/cdisc-org/conformance-rules-editor/assets/113539111/49741b3d-8860-4c7b-bd58-fdca1b3c8f82">

**Comment by RamilCDISC** [comment]
### VALIDATION SUMMARY
### Validation Methodology
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:

**Rule Editor Testing:** The rule editor online in the production was used to  validate the changes for all connected issues in the PR

**Code Review:**
The code files were reviewed for following: 
- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution
The tests were executed in the following order:

**Code Review**: The code for all the changes files was reviewed first to check the proper implementation of the Acceptance criteria.

**Rules Editor**: The Editor in production was first of all checked for availability of diff button. Then changes were made to a rule to see if the diff tab identifies the correct changes from the previously saved code. Then it was made sure that the code is in read only mode in the diff tab. It was also checked that the rule folds correctly when clicked fold level 1 in the right click menu option. 

**Regression Tests**: The regression tests were then run to confirm that the changes in engine did not break any other part of the implementation
### Results:
After successful running of all tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.
### Deviations and Non-conformances:
No deviations or non-conformances were observed.

### Summary of Findings:
**Test Results:** All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression**: The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
