### ISSUE TITLE
add and enforce yaml property sort order

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/conformance-rules-editor#143]
This will improve readability
AC:
- Property Sort order is stored in the json-schema via additional properties
- When a yaml rule is saved, the properties are sorted according to the sort order

**Comment by RamilCDISC** [comment]
### VALIDATION SUMMARY
### Validation Methodology
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:

**Rule Editor Testing**: The rule editor online in the production was used to validate the changes for all connected issues in the PR

**Code Review:**
The code files were reviewed for following:

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution
The tests were executed in the following order:

**Code Review**: The code for all the changed files was reviewed first to check the proper implementation of the Acceptance criteria.

**Rules Editor**: The Editor in production was first of all checked for proper folding when fold level 1 is clicked from the right click menu. Then the editor was checked to see if it retains the fold when we switch tabs , it was also checked if editor auto corrects the wrong  indentation.

**Regression Tests:** The regression tests were then run to confirm that the changes in engine did not break any other part of the implementation

### Results:
After successful running of all tests and careful validation, the issue was found to be good to close as the Acceptance criteria was fulfilled and all validations passed.

### Deviations and Non-conformances:
No deviations or non-conformances were observed.

### Summary of Findings:
**Test Results**: All tests conducted during the validation process passed successfully, indicating that the system functions as intended and meets the specified requirements. The tests covered various scenarios and edge cases, providing confidence in the system's reliability and correctness.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews**: The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
