### ISSUE TITLE
add new operators/operations to schema

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/conformance-rules-editor#170]
For example, domain_label

AC:
Any operators, operations, rule types, and parameters that exist in the core rules engine or business rules also exist in the rules editor schema

**Comment by RamilCDISC** [comment]
The acceptance criteria is not yet fulfilled for this issue. The following operations/operators were not found in schema ‘CORE-base.json’. 
**Rules Engine operation**: variable_is_null, valid_codelist_dates
**business rules operators:** is_true, is_false, deos_not_have_next_crossponding_record, num_equal_to, str_equal_to, num_not_euqal_to, str_not_equal_to

**Comment by RamilCDISC** [comment]
I do not see any new changes in the already connected PR, nor any new PR is connected. Also I have noticed that schema (CORE-base.json) is missing from the public folder in the conformance rules editor repository. Has the schema moved to somewhere else?

**Comment by nhaydel** [comment]
It has been moved here: https://github.com/cdisc-org/cdisc-rules-engine/blob/main/resources/schema/CORE-base.json also this issue was done before the latest schema update PRs so there shouldn't be any new changes. This likely can be moved to done

**Comment by RamilCDISC** [comment]
### Validation Summary

### Validation Methodology:
The validation process incorporated rigorous testing methodologies to ensure the accuracy and reliability of the system. This included:
**Manual Testing:**
Manual Testing was done to verify the implementation of the Acceptance criteria. 

**Code Review:**
The code changes in the code files were reviewed and were found to be in accordance with the Acceptance criteria. Also, the code was reviewed for following: 

- Code Quality Evaluation
- Logic and Functionality Review
- Error Handling and Exception Handling Assessment
- Security Considerations

**Regression Testing:**
Regression tests were run to validate that the changes did not affect any functionality of the overall system.

### Test Execution:
The core-base.json (schema) file was manually checked for each operator in business and core repositories. It was validated that each operator is available the schema.


### Results:
After successful running of manual and regression tests and careful validation, the issue was found not good to close as the Acceptance criteria was not fulfilled initially. There were some operators which were missing (refer to above comment from QA to see those operators).  Later on Schema was moved to CORE for another issue, so this issue was then closed so that the missing operators can be handled separately.

### Deviations and Non-conformances:
No deviations or non-conformances were observed.
### Summary of Findings:
**Test Results:** All tests conducted during the validation process did not pass initially because of missing operators in schema. Later on due to movement of schema this issue was closed.
**Unit Regression:** The unit regression tests were executed, and no regressions or issues were identified. This indicates that the changes made during the development or modification of the system did not introduce any unintended side effects or break existing functionality.
**Code Reviews:** The code reviews conducted by both development and QA teams were completed, and no major issues or concerns were identified. The code adheres to coding standards and best practices, demonstrating good code quality, readability, and maintainability.
